### ISSUE TITLE
ipone真机上时间组件时间出错，只能选择一个时间点

### ISSUE THREAD

**Issue by jdevsean** [79458627/ttyy-calendar#5]
点击时间组件时，只有一个时间可以选，但在开发者的ipone的模拟机型上是没问题的，安卓端都没问题
![image](https://user-images.githubusercontent.com/26438287/48173760-256b4800-e340-11e8-98ba-2ccbf765b3f7.png)

已经提到微信开发者上面了：
https://developers.weixin.qq.com/community/develop/doc/000aa842748fd8fd1ca7bdf355e400

**Comment by jdevsean** [comment]
貌似ipone机都出现了这个问题，基础库版本小程序设置是1.0.0

**Comment by rangang** [comment]
检查一下开始时间和结束时间的字段对吗
